/* site actions */
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

/* institution actions */
export const INSTITUTIONS_GET_ALL         = 'INSTITUTIONS_GET_ALL';
export const INSTITUTIONS_GET_ALL_SUCCESS = 'INSTITUTIONS_GET_ALL_SUCCESS';
export const INSTITUTIONS_GET_ALL_ERROR   = 'INSTITUTIONS_GET_ALL_ERROR';

export const INSTITUTION_GET         = 'INSTITUTION_GET';
export const INSTITUTION_GET_SUCCESS = 'INSTITUTION_GET_SUCCESS';
export const INSTITUTION_GET_ERROR   = 'INSTITUTION_GET_ERROR';

