export const institutionActions = {
  GET_ALL_INSTITUTIONS: 'GET_ALL_INSTITUTIONS',
  GET_ALL_INSTITUTIONS_SUCCESS: 'GET_ALL_INSTITUTIONS_SUCCESS',
  GET_ALL_INSTITUTIONS_ERROR: 'GET_ALL_INSTITUTIONS_ERROR',
  GO_TO_INSTITUTION: 'GO_TO_INSTITUTION',
  GO_TO_INSTITUTION_SUCCESS: 'GO_TO_INSTITUTION_SUCCESS'
};